[build-system]
requires = [
   "pyfiglet",
  "pygame",
  "setuptools",
  "wheel",
  "build",
  "coverage", 
  "doit",
   "flake8", 
   "pydocstyle",
    "pymin-reqs",
    "Sphinx"
]


build-backend = "setuptools.build_meta" 